"""Wiring diagram generation and export for Arduino projects.

Provides utilities to save wiring diagrams in multiple formats:
- Markdown (.md) - Human-readable wiring instructions
- JSON (.json) - Structured data for programmatic access
- SVG (.svg) - Visual diagram (placeholder/future implementation)
"""

import json
import os
from typing import Dict, List, Any, Optional


def parse_wiring_connections(wiring_text: str) -> List[Dict[str, str]]:
    """Parse wiring diagram text into structured connections.
    
    Looks for patterns like:
    - Component Pin -> Arduino Pin
    - Component -> Arduino (Description)
    """
    connections = []
    lines = wiring_text.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#') or line.startswith('='):
            continue
        
        # Pattern: "Component Pin -> Arduino Pin" or "Component -> Arduino"
        if '->' in line or '→' in line:
            separator = '->' if '->' in line else '→'
            parts = line.split(separator)
            if len(parts) == 2:
                from_part = parts[0].strip()
                to_part = parts[1].strip()
                
                connections.append({
                    "from": from_part,
                    "to": to_part,
                    "description": line
                })
        # Pattern: "Pin: Description" or "- Pin: Description"
        elif ':' in line:
            line_clean = line.lstrip('- ').strip()
            if ':' in line_clean:
                pin, desc = line_clean.split(':', 1)
                connections.append({
                    "pin": pin.strip(),
                    "description": desc.strip()
                })
    
    return connections


def save_wiring_diagram_json(
    wiring_diagram_text: str,
    additional_info: str,
    output_path: str,
    platform: str = "arduino-mega-2560-r3"
) -> str:
    """Save wiring diagram as structured JSON.
    
    Args:
        wiring_diagram_text: Raw wiring diagram text
        additional_info: Additional setup/component information
        output_path: Path to save JSON file
        platform: Target platform identifier
        
    Returns:
        Path to saved JSON file
    """
    connections = parse_wiring_connections(wiring_diagram_text)
    
    diagram_data = {
        "platform": platform,
        "wiring_diagram": {
            "raw_text": wiring_diagram_text,
            "connections": connections
        },
        "additional_info": additional_info,
        "metadata": {
            "format_version": "1.0",
            "generator": "agent_arduino"
        }
    }
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(diagram_data, f, indent=2, ensure_ascii=False)
    
    print(f"💾 Saved wiring diagram JSON: {output_path}")
    return output_path


def save_wiring_diagram_markdown(
    wiring_diagram_text: str,
    additional_info: str,
    output_path: str,
    project_name: str = "Arduino Project"
) -> str:
    """Save wiring diagram as formatted Markdown.
    
    Args:
        wiring_diagram_text: Raw wiring diagram text
        additional_info: Additional setup/component information
        output_path: Path to save Markdown file
        project_name: Name of the project
        
    Returns:
        Path to saved Markdown file
    """
    markdown_content = f"""# {project_name} - Wiring Diagram

## Hardware Connections

{wiring_diagram_text}

## Additional Setup Information

{additional_info}

## Notes

- Double-check all connections before powering on
- Ensure correct voltage levels (5V/3.3V) for components
- Use appropriate current-limiting resistors where needed
- Refer to component datasheets for pin configurations

---
*Generated by agent_arduino*
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(markdown_content)
    
    print(f"📄 Saved wiring diagram Markdown: {output_path}")
    return output_path


def generate_arduino_svg_placeholder(
    connections: List[Dict[str, str]],
    output_path: str,
    platform: str = "arduino-mega-2560-r3"
) -> str:
    """Generate a placeholder SVG for Arduino wiring diagram.
    
    Future implementation: Create visual SVG diagram of connections.
    For now, generates a text-based SVG placeholder.
    
    Args:
        connections: List of parsed connections
        output_path: Path to save SVG file
        platform: Target platform identifier
        
    Returns:
        Path to saved SVG file
    """
    # Placeholder SVG with text representation
    svg_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600" viewBox="0 0 800 600">
  <rect width="800" height="600" fill="#f8f9fa"/>
  
  <text x="400" y="50" font-size="24" font-weight="bold" text-anchor="middle" fill="#333">
    {platform.upper()} Wiring Diagram
  </text>
  
  <text x="400" y="100" font-size="16" text-anchor="middle" fill="#666">
    Visual diagram generation - Coming soon
  </text>
  
  <text x="50" y="150" font-size="14" font-weight="bold" fill="#333">
    Connections:
  </text>
"""
    
    y_offset = 180
    for i, conn in enumerate(connections[:20]):  # Limit to 20 connections
        if "from" in conn and "to" in conn:
            text = f"{conn['from']} → {conn['to']}"
        elif "pin" in conn:
            text = f"{conn['pin']}: {conn.get('description', '')[:40]}"
        else:
            text = conn.get('description', '')[:60]
        
        svg_content += f'  <text x="70" y="{y_offset}" font-size="12" fill="#444">{text}</text>\n'
        y_offset += 20
    
    svg_content += """
  <text x="400" y="560" font-size="12" text-anchor="middle" fill="#999">
    Refer to WIRING.md for complete connection details
  </text>
</svg>
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(svg_content)
    
    print(f"🎨 Saved wiring diagram SVG placeholder: {output_path}")
    return output_path


def save_wiring_diagram_all_formats(
    wiring_diagram_text: str,
    additional_info: str,
    project_dir: str,
    project_name: str = "Arduino Project",
    platform: str = "arduino-mega-2560-r3"
) -> Dict[str, str]:
    """Save wiring diagram in all supported formats.
    
    Args:
        wiring_diagram_text: Raw wiring diagram text
        additional_info: Additional setup/component information
        project_dir: Directory to save files
        project_name: Name of the project
        platform: Target platform identifier
        
    Returns:
        Dictionary mapping format names to file paths
    """
    saved_files = {}
    
    # Ensure project directory exists
    os.makedirs(project_dir, exist_ok=True)
    
    # Save Markdown
    md_path = os.path.join(project_dir, "WIRING.md")
    saved_files['markdown'] = save_wiring_diagram_markdown(
        wiring_diagram_text,
        additional_info,
        md_path,
        project_name
    )
    
    # Save JSON
    json_path = os.path.join(project_dir, "wiring_diagram.json")
    saved_files['json'] = save_wiring_diagram_json(
        wiring_diagram_text,
        additional_info,
        json_path,
        platform
    )
    
    # Save SVG placeholder
    connections = parse_wiring_connections(wiring_diagram_text)
    svg_path = os.path.join(project_dir, "wiring_diagram.svg")
    saved_files['svg'] = generate_arduino_svg_placeholder(
        connections,
        svg_path,
        platform
    )
    
    print(f"✅ Saved wiring diagrams in {len(saved_files)} formats")
    return saved_files
